base: 'http://localhost/typo3-project/public/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 6
websiteTitle: 'My first web Site'
